### PR TITLE
Fix parents route fetching unreleased parents

### LINKED ISSUE #254: Fetch parents route fetches unreleased parents
The fetch parents route needs to be updated to:
- Return only released parents if the user has no privileged access 
- Return parents in the working stage if the user is an admin/editor/curator@collection/reviewer@collection

### PR DESCRIPTION
**Pull request by gshaw1997**
This PR fixes the issue where unreleased parent Learning Objects were returned for unauthorized users when making a request to fetch parents.

Closes #254

### CODE REVIEW

File: src/interactors/LearningObjectInteractor.ts [hunk 1]
```diff
@@ -657,19 +661,72 @@ export class LearningObjectInteractor {
...
+          full,
+        });
+      }
+      return [];
     } catch (e) {
-      console.log(e);
-      return Promise.reject(
-        `Problem fetching parent objects for ${params.query.id}. Error: ${e}`,
-      );
+      if (e instanceof ResourceError || e instanceof ServiceError) {
```
Comment (DonSeannelly) [inline src/interactors/LearningObjectInteractor.ts]: This seems to be a very common block of code. Maybe we should consider putting this into a function, that way we can simplify all the catch blocks that use it? Probably out of scope for this PR, I just wanted to bring up the idea.

File: test_environment/globalConfig.json [hunk 2]
```diff
@@ -1 +1 @@
-{"mongoUri":"mongodb://127.0.0.1:55321/4775168c-2d44-4d48-b6b7-bc2ff8589740"}
+{"mongoUri":"mongodb://127.0.0.1:42627/17987b01-949b-45b2-b31a-541af53a0650"}
```
Comment (DonSeannelly) [inline test_environment/globalConfig.json]: We should add this to the .gitignore - it's a build artifact of the test runner and doesn't have any meaning between systems.

Comment (gshaw1997) [reply test_environment/globalConfig.json]: This was added to the .gitignore. It needed to be removed from the cache.
