### PR TITLE
Fix Learning Objects not being found if the released copy's name was different from working copy's name

### LINKED ISSUE #250: Editing a released Learning Object's name causes released object to not be found
When an admin/editor edits a released Learning Object's name, the released object is not found.

### PR DESCRIPTION
**Pull request by gshaw1997**
This PR fixes the issue where Learning Objects could not be found if released copy's name was different from working copy's name.

Closes #250

### CODE REVIEW

File: src/interactors/LearningObjectInteractor.ts [hunk 1]
```diff
@@ -231,22 +231,27 @@ export class LearningObjectInteractor {
 
       const fullChildren = false;
       let loadWorkingCopies = false;
-      const learningObjectID = await dataStore.findLearningObject(
-        username,
-        learningObjectName,
-      );
+
+      const proceedIfPrivileged = (e: Error): null => {
```
Comment (DonSeannelly) [inline src/interactors/LearningObjectInteractor.ts]: A comment here describing the use of the error handler would be helpful

Comment (DonSeannelly) [reply src/interactors/LearningObjectInteractor.ts]: For instance, why return null over just having a void return type? How is this intended to be used.

File: src/interactors/LearningObjectInteractor.ts [hunk 2]
```diff
@@ -622,58 +803,72 @@ export class LearningObjectInteractor {
...
+      const objectIds = objectRefs.map(obj => obj.id);
+      // Remove objects from library
+      await library.cleanObjectsFromLibraries(objectIds);
+      // Delete objects from datastore
+      await dataStore.deleteMultipleLearningObjects(objectIds);
+      // For each object id
+      objectRefs.forEach(async obj => {
+        // Attempt to delete files
+        const path = `${user.username}/${obj.id}/`;
+        fileManager.deleteAll({ path }).catch(e => {
```
Comment (DonSeannelly) [inline src/interactors/LearningObjectInteractor.ts]: We should report this error out to sentry as well so we don't have to check logs manually.
